### ISSUE TITLE
Testes Unitários no SICRED não estão passando

### ISSUE THREAD

**Issue by olavorn** [BoletoNet/BoletoNetCore#4]
Algum interessado que trabalhe com o SICRED? 

Verificar porque os testes no SICRED não estão passando.

**Comment by rafd75** [comment]
Vixe, esse é o único banco que não utilizo aqui... 

Não tenho nenhum exemplo válido para fazer o teste fechar.

**Comment by carloscds** [comment]
@olavorn Pode fixar o teste?

**Comment by olavorn** [comment]
```  log
D:\Dev\BoletoNetCore>dotnet test
Build iniciada, aguarde...
Build iniciada, aguarde...
Build iniciada, aguarde...
Build concluído.

Skipping running test for project D:\Dev\BoletoNetCore\Boleto2.Net\Boleto2.Net.csproj. To run tests with dotnet test add "<IsTestProject>true<IsTestProject>" property to project file.
Skipping running test for project D:\Dev\BoletoNetCore\Boleto2.Net\Boleto2.Net.csproj. To run tests with dotnet test add "<IsTestProject>true<IsTestProject>" property to project file.
Build concluído.

Execução de teste para D:\Dev\BoletoNetCore\Boleto2.Net.Testes\bin\Debug\netcoreapp2.2\Boleto2.Net.Testes.dll(.NETCoreApp,Version=v2.2)
Microsoft (R) Test Execution Command Line Tool Version 15.9.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
Build concluído.

Skipping running test for project D:\Dev\BoletoNetCore\Boleto2.Net.Pdf\Boleto2.Net.Pdf.csproj. To run tests with dotnet test add "<IsTestProject>true<IsTestProject>" property to project file.
Skipping running test for project D:\Dev\BoletoNetCore\Boleto2.Net.Pdf\Boleto2.Net.Pdf.csproj. To run tests with dotnet test add "<IsTestProject>true<IsTestProject>" property to project file.
Failed   Sicredi_1_01_BoletoOK(500,"4","4","4","19/200004-8","74894629800000500001119200004801560585305103","74891.11927 00004.801569 05853.051034 4 62980000050000",2015,1,4)
Error Message:
 System.Exception : Nosso número (4) deve conter 9 dígitos.
Stack Trace:
   at Boleto2Net.BancoSicrediCarteira1.FormataNossoNumero(Boleto boleto) in D:\Dev\BoletoNetCore\Boleto2.Net\Banco\Carteiras\BancoSicredi\BancoSicrediCarteira1.cs:line 48
   at Boleto2Net.BancoSicredi.FormataNossoNumero(Boleto boleto) in D:\Dev\BoletoNetCore\Boleto2.Net\Banco\BancoSicredi.cs:line 39
   at Boleto2Net.Boleto.ValidarDados() in D:\Dev\BoletoNetCore\Boleto2.Net\Boleto\Boleto.cs:line 155
   at Boleto2Net.Testes.BancoSicrediCarteira1Tests.Sicredi_1_01_BoletoOK(Decimal valorTitulo, String nossoNumero, String numeroDocumento, String digitoVerificador, String nossoNumeroFormatado, String codigoDeBarras, String linhaDigitavel, Int32[] anoMesDia) in D:\Dev\BoletoNetCore\Boleto2.Net.Testes\BancoSicrediCarteira1Tests.cs:line 60
Failed   Sicredi_1_01_BoletoOK(400,"3","4","4","19/200003-0","74894740700000400001119200003001560585305101","74891.11927 00003.001567 05853.051018 4 74070000040000",2018,1,17)
Error Message:
 System.Exception : Nosso número (3) deve conter 9 dígitos.
Stack Trace:
   at Boleto2Net.BancoSicrediCarteira1.FormataNossoNumero(Boleto boleto) in D:\Dev\BoletoNetCore\Boleto2.Net\Banco\Carteiras\BancoSicredi\BancoSicrediCarteira1.cs:line 48
   at Boleto2Net.BancoSicredi.FormataNossoNumero(Boleto boleto) in D:\Dev\BoletoNetCore\Boleto2.Net\Banco\BancoSicredi.cs:line 39
   at Boleto2Net.Boleto.ValidarDados() in D:\Dev\BoletoNetCore\Boleto2.Net\Boleto\Boleto.cs:line 155
   at Boleto2Net.Testes.BancoSicrediCarteira1Tests.Sicredi_1_01_BoletoOK(Decimal valorTitulo, String nossoNumero, String numeroDocumento, String digitoVerificador, String nossoNumeroFormatado, String codigoDeBarras, String linhaDigitavel, Int32[] anoMesDia) in D:\Dev\BoletoNetCore\Boleto2.Net.Testes\BancoSicrediCarteira1Tests.cs:line 60
Failed   Sicredi_1_01_BoletoOK(800,"10","10","3","19/200010-2","74893787000000800001119200010201560585305102","74891.11927 00010.201564 05853.051026 3 78700000080000",2019,4,25)
Error Message:
 System.Exception : Nosso número (10) deve conter 9 dígitos.
Stack Trace:
   at Boleto2Net.BancoSicrediCarteira1.FormataNossoNumero(Boleto boleto) in D:\Dev\BoletoNetCore\Boleto2.Net\Banco\Carteiras\BancoSicredi\BancoSicrediCarteira1.cs:line 48
   at Boleto2Net.BancoSicredi.FormataNossoNumero(Boleto boleto) in D:\Dev\BoletoNetCore\Boleto2.Net\Banco\BancoSicredi.cs:line 39
   at Boleto2Net.Boleto.ValidarDados() in D:\Dev\BoletoNetCore\Boleto2.Net\Boleto\Boleto.cs:line 155
   at Boleto2Net.Testes.BancoSicrediCarteira1Tests.Sicredi_1_01_BoletoOK(Decimal valorTitulo, String nossoNumero, String numeroDocumento, String digitoVerificador, String nossoNumeroFormatado, String codigoDeBarras, String linhaDigitavel, Int32[] anoMesDia) in D:\Dev\BoletoNetCore\Boleto2.Net.Testes\BancoSicrediCarteira1Tests.cs:line 60
Failed   Sicredi_1_01_BoletoOK(900,"9","9","6","19/200009-9","74896787700000900001119200009901560585305100","74891.11927 00009.901562 05853.051000 6 78770000090000",2019,5,2)
Error Message:
 System.Exception : Nosso número (9) deve conter 9 dígitos.
Stack Trace:
   at Boleto2Net.BancoSicrediCarteira1.FormataNossoNumero(Boleto boleto) in D:\Dev\BoletoNetCore\Boleto2.Net\Banco\Carteiras\BancoSicredi\BancoSicrediCarteira1.cs:line 48
   at Boleto2Net.BancoSicredi.FormataNossoNumero(Boleto boleto) in D:\Dev\BoletoNetCore\Boleto2.Net\Banco\BancoSicredi.cs:line 39
   at Boleto2Net.Boleto.ValidarDados() in D:\Dev\BoletoNetCore\Boleto2.Net\Boleto\Boleto.cs:line 155
   at Boleto2Net.Testes.BancoSicrediCarteira1Tests.Sicredi_1_01_BoletoOK(Decimal valorTitulo, String nossoNumero, String numeroDocumento, String digitoVerificador, String nossoNumeroFormatado, String codigoDeBarras, String linhaDigitavel, Int32[] anoMesDia) in D:\Dev\BoletoNetCore\Boleto2.Net.Testes\BancoSicrediCarteira1Tests.cs:line 60
Failed   Sicredi_1_01_BoletoOK(603.56d,"5","5","6","19/200005-6","74896790500000603561119200005601560585305109","74891.11927 00005.601562 05853.051091 6 79050000060356",2019,5,30)
Error Message:
 System.Exception : Nosso número (5) deve conter 9 dígitos.
Stack Trace:
   at Boleto2Net.BancoSicrediCarteira1.FormataNossoNumero(Boleto boleto) in D:\Dev\BoletoNetCore\Boleto2.Net\Banco\Carteiras\BancoSicredi\BancoSicrediCarteira1.cs:line 48
   at Boleto2Net.BancoSicredi.FormataNossoNumero(Boleto boleto) in D:\Dev\BoletoNetCore\Boleto2.Net\Banco\BancoSicredi.cs:line 39
   at Boleto2Net.Boleto.ValidarDados() in D:\Dev\BoletoNetCore\Boleto2.Net\Boleto\Boleto.cs:line 155
   at Boleto2Net.Testes.BancoSicrediCarteira1Tests.Sicredi_1_01_BoletoOK(Decimal valorTitulo, String nossoNumero, String numeroDocumento, String digitoVerificador, String nossoNumeroFormatado, String codigoDeBarras, String linhaDigitavel, Int32[] anoMesDia) in D:\Dev\BoletoNetCore\Boleto2.Net.Testes\BancoSicrediCarteira1Tests.cs:line 60
Failed   Sicredi_1_01_BoletoOK(300,"2","2","7","19/200002-1","74897790500000300001119200002101560585305102","74891.11927 00002.101566 05853.051026 7 79050000030000",2019,5,30)
Error Message:
 System.Exception : Nosso número (2) deve conter 9 dígitos.
Stack Trace:
   at Boleto2Net.BancoSicrediCarteira1.FormataNossoNumero(Boleto boleto) in D:\Dev\BoletoNetCore\Boleto2.Net\Banco\Carteiras\BancoSicredi\BancoSicrediCarteira1.cs:line 48
   at Boleto2Net.BancoSicredi.FormataNossoNumero(Boleto boleto) in D:\Dev\BoletoNetCore\Boleto2.Net\Banco\BancoSicredi.cs:line 39
   at Boleto2Net.Boleto.ValidarDados() in D:\Dev\BoletoNetCore\Boleto2.Net\Boleto\Boleto.cs:line 155
   at Boleto2Net.Testes.BancoSicrediCarteira1Tests.Sicredi_1_01_BoletoOK(Decimal valorTitulo, String nossoNumero, String numeroDocumento, String digitoVerificador, String nossoNumeroFormatado, String codigoDeBarras, String linhaDigitavel, Int32[] anoMesDia) in D:\Dev\BoletoNetCore\Boleto2.Net.Testes\BancoSicrediCarteira1Tests.cs:line 60
Failed   Sicredi_1_01_BoletoOK(200,"6","6-1/3","5","19/200006-4","74895810800000200001119200006401560585305104","74891.11927 00006.401566 05853.051042 5 81080000020000",2019,12,19)
Error Message:
 System.Exception : Nosso número (6) deve conter 9 dígitos.
Stack Trace:
   at Boleto2Net.BancoSicrediCarteira1.FormataNossoNumero(Boleto boleto) in D:\Dev\BoletoNetCore\Boleto2.Net\Banco\Carteiras\BancoSicredi\BancoSicrediCarteira1.cs:line 48
   at Boleto2Net.BancoSicredi.FormataNossoNumero(Boleto boleto) in D:\Dev\BoletoNetCore\Boleto2.Net\Banco\BancoSicredi.cs:line 39
   at Boleto2Net.Boleto.ValidarDados() in D:\Dev\BoletoNetCore\Boleto2.Net\Boleto\Boleto.cs:line 155
   at Boleto2Net.Testes.BancoSicrediCarteira1Tests.Sicredi_1_01_BoletoOK(Decimal valorTitulo, String nossoNumero, String numeroDocumento, String digitoVerificador, String nossoNumeroFormatado, String codigoDeBarras, String linhaDigitavel, Int32[] anoMesDia) in D:\Dev\BoletoNetCore\Boleto2.Net.Testes\BancoSicrediCarteira1Tests.cs:line 60
Failed   Sicredi_1_01_BoletoOK(200,"7","6-2/3","8","19/200007-2","74898813900000200001119200007201560585305100","74891.11927 00007.201569 05853.051000 8 81390000020000",2020,1,19)
Error Message:
 System.Exception : Nosso número (7) deve conter 9 dígitos.
Stack Trace:
   at Boleto2Net.BancoSicrediCarteira1.FormataNossoNumero(Boleto boleto) in D:\Dev\BoletoNetCore\Boleto2.Net\Banco\Carteiras\BancoSicredi\BancoSicrediCarteira1.cs:line 48
   at Boleto2Net.BancoSicredi.FormataNossoNumero(Boleto boleto) in D:\Dev\BoletoNetCore\Boleto2.Net\Banco\BancoSicredi.cs:line 39
   at Boleto2Net.Boleto.ValidarDados() in D:\Dev\BoletoNetCore\Boleto2.Net\Boleto\Boleto.cs:line 155
   at Boleto2Net.Testes.BancoSicrediCarteira1Tests.Sicredi_1_01_BoletoOK(Decimal valorTitulo, String nossoNumero, String numeroDocumento, String digitoVerificador, String nossoNumeroFormatado, String codigoDeBarras, String linhaDigitavel, Int32[] anoMesDia) in D:\Dev\BoletoNetCore\Boleto2.Net.Testes\BancoSicrediCarteira1Tests.cs:line 60
Failed   Sicredi_1_01_BoletoOK(200,"8","6-3/3","4","19/200008-0","74894817000000200001119200008001560585305105","74891.11927 00008.001562 05853.051059 4 81700000020000",2020,2,19)
Error Message:
 System.Exception : Nosso número (8) deve conter 9 dígitos.
Stack Trace:
   at Boleto2Net.BancoSicrediCarteira1.FormataNossoNumero(Boleto boleto) in D:\Dev\BoletoNetCore\Boleto2.Net\Banco\Carteiras\BancoSicredi\BancoSicrediCarteira1.cs:line 48
   at Boleto2Net.BancoSicredi.FormataNossoNumero(Boleto boleto) in D:\Dev\BoletoNetCore\Boleto2.Net\Banco\BancoSicredi.cs:line 39
   at Boleto2Net.Boleto.ValidarDados() in D:\Dev\BoletoNetCore\Boleto2.Net\Boleto\Boleto.cs:line 155
   at Boleto2Net.Testes.BancoSicrediCarteira1Tests.Sicredi_1_01_BoletoOK(Decimal valorTitulo, String nossoNumero, String numeroDocumento, String digitoVerificador, String nossoNumeroFormatado, String codigoDeBarras, String linhaDigitavel, Int32[] anoMesDia) in D:\Dev\BoletoNetCore\Boleto2.Net.Testes\BancoSicrediCarteira1Tests.cs:line 60
Failed   Sicredi_1_REM400
Error Message:
 System.Exception : Nosso número (92) deve conter 9 dígitos.
Stack Trace:
   at Boleto2Net.BancoSicrediCarteira1.FormataNossoNumero(Boleto boleto) in D:\Dev\BoletoNetCore\Boleto2.Net\Banco\Carteiras\BancoSicredi\BancoSicrediCarteira1.cs:line 48
   at Boleto2Net.BancoSicredi.FormataNossoNumero(Boleto boleto) in D:\Dev\BoletoNetCore\Boleto2.Net\Banco\BancoSicredi.cs:line 39
   at Boleto2Net.Boleto.ValidarDados() in D:\Dev\BoletoNetCore\Boleto2.Net\Boleto\Boleto.cs:line 155
   at Boleto2Net.Testes.Utils.GerarBoleto(IBanco banco, Int32 i, String aceite, Int32 NossoNumeroInicial) in D:\Dev\BoletoNetCore\Boleto2.Net.Testes\Utils.cs:line 142
   at Boleto2Net.Testes.Utils.GerarBoletos(IBanco banco, Int32 quantidadeBoletos, String aceite, Int32 NossoNumeroInicial) in D:\Dev\BoletoNetCore\Boleto2.Net.Testes\Utils.cs:line 79
   at Boleto2Net.Testes.Utils.TestarHomologacao(IBanco banco, TipoArquivo tipoArquivo, String nomeCarteira, Int32 quantidadeBoletos, Boolean gerarBoletoPdfHtml, String aceite, Int32 NossoNumeroInicial) in D:\Dev\BoletoNetCore\Boleto2.Net.Testes\Utils.cs:line 150
   at Boleto2Net.Testes.BancoSicrediCarteira1Tests.Sicredi_1_REM400() in D:\Dev\BoletoNetCore\Boleto2.Net.Testes\BancoSicrediCarteira1Tests.cs:line 34

Total tests: 130. Passed: 120. Failed: 10. Skipped: 0.
Test Run Failed.
Test execution time: 1,4993 Minutes
```
Ele passava na versão original?

**Comment by carloscds** [comment]
@olavorn Nao esta quebrando no build.

**Comment by olavorn** [comment]
@carloscds não mesmo... buildando normal. E os outros testes passam todos.
Ele só não tá passando os testes do Sicredi mesmo, mas vi que a construção do Nosso número lá tá meio zoada..
```
Total tests: 130. Passed: 120. Failed: 10. Skipped: 0.
```

**Comment by olavorn** [comment]
Seria bom marcar adicionar uma tag "Help Wanted" nessa issue...

**Comment by carloscds** [comment]
@rafd75 Poderia verificar ?

**Comment by carloscds** [comment]
@olavorn @rafd75 A ultima alteração no método que está quebrando o teste foi feita pelo @denerkrebs

**Comment by olavorn** [comment]
Mas teria como confirmar se na branch original esses testes passavam?

**Comment by carloscds** [comment]
@olavorn Nao esta passando.

**Comment by rafd75** [comment]
> @olavorn @rafd75 A ultima alteração no método que está quebrando o teste foi feita pelo @denerkrebs

@carloscds - Como eu não tenho sicred aqui (em produção), não tenho como garantir que o teste é válido.

Normalmente, para gerar um teste, eu primeiro faço a homologação com o banco, e considerando que está correto, gero 9 boletos com diferentes dígitos da linha digitavel (de 1 a 9) e vou alterando os valores até bater.

Melhor que alguém que tenha em produção faça isso.

Talvez o @marcosgerene (não sei como linkar ele aqui nesse projeto) pode ajudar...
Ele está fazendo ajustes no Sicred do Boleto2Net
Vou mandar um email para ele...

**Comment by marcosgerene** [comment]
@rafd75 estamos validando o boleto, o único erro que tivemos foi por causa da duplicata mercantil, a qual fiz um PR...

Não sei se é ultil a informação, mas só está implementado o CNAB400 do Sicredi.

Vou tentar entender o problema teste unitário e vou validar meus boletos no banco, posto os resultados aqui

**Comment by marcosgerene** [comment]
@rafd75 boletos validados.

**Comment by olavorn** [comment]
dotnet test

**Comment by carloscds** [comment]
@marcosgerene Faz o Build all da Solution e depois rode os testes. Testes executados com sucesso ficam em verde e com erro em vermelho. NA sua imagem parece nao terem rodado.

**Comment by olavorn** [comment]
![image](https://user-images.githubusercontent.com/3752407/61760101-c26ff300-ada0-11e9-9659-ccd10662d0da.png)
(Na branch do projeto renomeado) @marcosgerene aguardando seu PR pra eu fazer um merge com a minha branch local.

**Comment by marcosgerene** [comment]
Caros,

Quanto aos testes, o core roda, o "normal" não.
![nao_roda_1](https://user-images.githubusercontent.com/15945003/61817734-9ba7d000-ae25-11e9-8471-a210ee7c45a9.gif)

![testes_core_1](https://user-images.githubusercontent.com/15945003/61817762-a82c2880-ae25-11e9-9641-02a4f5be743f.gif)

-------------------

Quanto ao teste (Core), segue o motivo:

![testes_core_motivo](https://user-images.githubusercontent.com/15945003/61817769-ad897300-ae25-11e9-87e3-ed54d6744169.gif)
