### ISSUE TITLE
Error ao chamar a função GetResourceHypertext()

### ISSUE THREAD

**Issue by jlfjunior** [BoletoNet/BoletoNetCore#63]
System.ArgumentNullException
  HResult=0x80004003
  Message=Value cannot be null. 
  Source=System.Private.CoreLib
  StackTrace:
   at System.IO.StreamReader..ctor(Stream stream, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean leaveOpen)
   at System.IO.StreamReader..ctor(Stream stream)
   at BoletoNetCore.BoletoBancario.GetResourceHypertext(String resourcePath)
   at BoletoNetCore.BoletoBancario.GeraHtmlCarne(String telefone, String htmlBoleto)
   at BoletoNetCore.BoletoBancario.MontaHtml(String urlImagemLogo, String urlImagemBarra, String imagemCodigoBarras)
   at BoletoNetCore.BoletoBancario.HtmlOffLine(String textoNoComecoDoEmail, String srcLogo, String srcBarra, String srcCodigoBarra, Boolean usaCsspdf)
   at BoletoNetCore.BoletoBancario.MontaHtmlEmbedded(Boolean convertLinhaDigitavelToImage, Boolean usaCsspdf, String urlImagemLogoBeneficiario)
   at BankSlip.Api.Models.Services.BankSlipService.GeneratePdf(IEnumerable`1 bankSlipsModels, Boolean paymentBooklet) in C:\Users\junior\Documents\PagCerto\BankSlip\src\BankSlip.Api\Models\Services\BankSlipService.cs:line 26
   at BankSlip.Api.Controllers.PrintController.GeneratePdf(BankSlipPdfModel model) in C:\Users\junior\Documents\PagCerto\BankSlip\src\BankSlip.Api\Controllers\PrintController.cs:line 18
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()

Como solucionar a ausência do .html na string "BoletoNetCore.BoletoImpressao.Parts.Carne"

**Comment by jlfjunior** [comment]
Problema corrigido a partir do **BoletoNetCore** versão 3.0.1.80.
