### ISSUE TITLE
Erro ao executar em ambiente linux

### ISSUE THREAD

**Issue by jlfjunior** [BoletoNet/BoletoNetCore#68]
Internal Server Error
System.ComponentModel.Win32Exception (13): Permission denied
   at Wkhtmltopdf.NetCore.WkhtmlDriver.Convert(String wkhtmlPath, String switches, String html)
   at Wkhtmltopdf.NetCore.GeneratePdf.GetPDF(String html)

**Comment by carloscds** [comment]
@jlfjunior Voce viu se tem uma pasta chamada Rotativa

**Comment by jlfjunior** [comment]
@carloscds Tem sim.

**Comment by carloscds** [comment]
@jlfjunior Isto pode ser problema de permissao no linux, tenta chmod 775 ou 777 na pasta.

**Comment by jlfjunior** [comment]
@carloscds já executei, mesmo assim o problema ocorre.

**Comment by marcianobandeira** [comment]
boa tarde @carloscds e @jlfjunior 

Estou utilizando o projeto em ambiente linux, e desenvolvi a impressão do boleto usando o projeto [QuestPDF](https://github.com/QuestPDF/library), que por sinal é muito bom, tenho utilizado para várias outras coisas aqui.

Para gerar o Código de Barras do boleto utilizei o projeto [Barcoder](https://github.com/huysentruitw/barcoder).

Por enquanto desenvolvi apenas a impressão em modo carnê que era minha necessidade atual, estou enviando um print de um boleto gerado para avialação dos senhores (Não posso disponibilizar o PDF em si por conter dados sensíveis).

![image](https://user-images.githubusercontent.com/1214521/135527802-a68ff42d-0dd6-4836-8e19-a88ebd89a551.png)

@carloscds caso ache que seja interessante para o projeto, posso preparar um pull request aqui, creio que a uma boa maneira seria criar um projeto BoletoNetCore.Pdf.QuestPDF (ou algum outro nome de preferencia) e adicionar os novos codigos dentro desse projeto, assim fica algo que pode ser acoplado ou não.

O legal deste QuestPDF que consegui gerar com sucesso em Windows, MacOS e Linux... no linux tive um problema inicialmente por falta de librarys, mas bastou adicionar referencia ao projeto SkiaSharp (SkiaSharp.NativeAssets.Linux) que é usado internamente pelo QuestPDF, que tudo funcionou perfeitamente.

**Comment by carloscds** [comment]
@marcianobandeira Se o componente for totalmente free e sem restrição de distribuição não vejo problema. Qual o tipo de licenca open source dele ?

**Comment by marcianobandeira** [comment]
@carloscds agora voce me apertou.. ambos os projetos estão disponíveis no github...
pelo que pude ver, todos eles (Barcoder, QuestPDF e Skiasharp) tem a licença como "MIT License", mas sinceramente não sei se preenche os requisitos esperados. No meu post acima tem o link dos projetos caso queira dar uma olhada.

**Comment by carloscds** [comment]
@marcianobandeira MIT e a mais permissiva!

**Comment by marcianobandeira** [comment]
legal, vou preparar o PR nos proximos dias e envio.

**Comment by Syndelis** [comment]
Encontrei essa conversa por acaso e percebi que o PR #158 já foi mergeado. Será que vale a pena fechar a discussão?

**Comment by carloscds** [comment]
@Syndelis sim.
